name = "ApproxFunSingularities"
uuid = "f8fcb915-6b99-5be2-b79a-d6dbef8e6e7e"
version = "0.1.9"

[deps]
ApproxFunBase = "fbd15aa5-315a-5a7d-a8a4-24992e37be05"
ApproxFunOrthogonalPolynomials = "b70543e2-c0d9-56b8-a290-0d4d6d4de211"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ApproxFunBase = "0.3.8"
ApproxFunOrthogonalPolynomials = "0.2.3, 0.3"
DomainSets = "0.4"
IntervalSets = "0.5"
Reexport = "0.2"
julia = "1"

[extras]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SpecialFunctions"]
